local Client = require("../src/client")

local client = Client.new("http://127.0.0.1:8080", "dev-key")
print(client:pending_tasks_request("game_client", 1).path)
print(client:claim_runtime_task_request("task-1", "game_client", "lua-sdk-example").body)
print(client:start_runtime_task_request("task-1", "lease-token").body)
print(client:heartbeat_runtime_task_request("task-1", "lease-token").body)
print(client:action_callback_request("callback-1", "success", '{"worker":"lua-sdk-example"}').body)
print(client:release_runtime_task_request("task-1", "lease-token", "manual release").body)
print(client:requeue_runtime_task_request("task-1", 1500, "manual requeue").body)
print(client:runtime_task_stats_request().path)
